blockMsg: "<red>You are not allowed to use this command"
disabled-commands:
  - pl
  - bukkit:pl
  - plugins
  - bukkit:plugins
  - ver
  - bukkit:ver
  - version
  - bukkit:version
  - "?"
  - bukkit:?
  - help
  - bukkit:help
  - about
  - bukkit:about
  - icanhasbukkit
  - bukkit:icanhasbukkit